services:
  # 服务 1: Flask 后端
  flask-app:
    build: .
    container_name: my-backend
    restart: always
    # 👇 【修改点1】不再写死密钥，改为读取 .env 文件
    # 这样服务器上就会用服务器的密钥，本地用本地的
    env_file:
      - .env
    volumes:
      - ./app.db:/app/app.db   # 数据库持久化
      - ./:/app                # 实时代码映射
    expose:
      - "5000"

  # 服务 2: Nginx 前端 + 反向代理
  nginx:
      image: nginx:alpine
      container_name: my-nginx
      restart: always
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx/flask.conf:/etc/nginx/conf.d/default.conf
        - /etc/letsencrypt:/etc/letsencrypt:ro
        # 👇 [新增] 将宿主机的验证目录挂载给 Nginx
        - /var/www/certbot:/var/www/certbot:ro
        - ./app/static:/app/app/static
        - ./frontend:/usr/share/nginx/html
      depends_on:
        - flask-app