"""add project progress

Revision ID: fe0150015ec2
Revises: ae19c1098cf3
Create Date: 2026-01-22 13:33:24.109030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0150015ec2'
down_revision = 'ae19c1098cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('count_fire', sa.Integer(), nullable=False),
    sa.Column('count_heart', sa.Integer(), nullable=False),
    sa.Column('count_rocket', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_update', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_update_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=False))
        batch_op.alter_column('is_published',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_published',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('progress')

    with op.batch_alter_table('project_update', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_update_timestamp'))

    op.drop_table('project_update')
    # ### end Alembic commands ###
